name: LuckyWars
version: 1.5.2
load: STARTUP
main: LuckyWars\LuckyWars
api: 4.0.0
author: [revape, protectoryt]
description: LuckyWars Minigame for your PocketMine-MP server

commands:
  lw:
    usage: /lw <leave-make>
    description: LuckyWars
  lwstart:
    usage: /lwstart
    description: Starts LuckyWars game
